name: ci
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
jobs:
  lint-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tooling
        run: |
          brew update
          brew install shellcheck shfmt bats-core
      - name: Lint
        run: |
          shellcheck -x bin/hostsctl.zsh
          shfmt -d -i 2 -ci -sr .
      - name: Test
        run: bats -r test
