name: ci
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
jobs:
  lint-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tooling
        run: |
          brew update
          brew install bats-core
      - name: Lint
        run: |
          zsh -n bin/hostsctl.zsh
      - name: Test
        run: bats -r test
